# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

redshift_default: &redshift_default
  redshift_host: <%= ENV.fetch('REDSHIFT_HOST', '') %>
  redshift_port: <%= ENV.fetch('REDSHIFT_PORT', 5439).to_i %>
  redshift_username: <%= ENV.fetch('REDSHIFT_USERNAME', '') %>
  redshift_password: <%= ENV.fetch('REDSHIFT_PASSWORD', '') %>
  redshift_database: <%= ENV.fetch('REDSHIFT_DATABASE', '') %>

development:
  <<: *redshift_default
  secret_key_base: aaa0d290e01278ef32a27b73698cc18b775727e945d1771099f0b376e8fd5079c3036259f9faeaa4804bc9dc0d9048c34164c229f2f6ad6aa7cdad554882efdd

test:
  <<: *redshift_default
  secret_key_base: 65b01a3ba79a3c4bd41c0cc548eda9586b53962d921b6b516b4b378ab6044fdbe6f76a24bc8e36c1e78718a15be93be598266efc1262c0a3be65663cced31c30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *redshift_default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
